name: Build container image
on:
  push:
    branches:
      - main

jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: docker build . --file Dockerfile --tag webapp

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/gleam-lang/packages
          TAG="$IMAGE_ID":"$BRANCH_NAME"
          docker tag webapp "$TAG"
          docker push "$TAG"

      - uses: actions/delete-package-versions@v5
        with: 
          package-name: 'packages'
          package-type: 'container'
          min-versions-to-keep: 10
          delete-only-untagged-versions: 'true'
